name: '$(Build.BuildId)  [$(Build.SourceBranchName)]  '

trigger:
  batch: true
  branches:
    include:
      - 'f9008874-f05d-4e9b-b30b-f034254069b8'
    exclude:
      - '*'

variables:
  - template: variables/base.yml

  # ///////////////////////////////////////////////////////////////////////////
  # // Pipeline Configuration /////////////////////////////////////////////////

  - { name: debug__print_configuration_variables, value: true }
  - { name: debug__print_artifact_version_information, value: true }
  - { name: debug__list_working_directory_content, value: false }

  # // @info disable husky in ci/cd environment
  - { name: HUSKY, value: 0 }

  # // stage: build configuration flags
  - { name: stage_build__enabled, value: true }
  - { name: stage_build__yarn_caching_is_enabled, value: true }
  - { name: stage_build__frontend_check_code_style, value: true }
  - { name: stage_build__frontend_analyse_code, value: true }
  - { name: stage_build__artifact_build, value: true }
  - { name: stage_build__artifact_test, value: true }
  - { name: stage_build__artifact_publish_test_results, value: true } # only true if 'stage_build__artifact_test' is also true
  - { name: stage_build__publish_artifact, value: true }

stages:
  - template: 'stages/CheckAndBuild.yml'
