steps:
  - bash: |
      /home/forge/bin/dfx stop
      . ${NVM_DIR}/nvm.sh 
      nvm use
      /home/forge/bin/dfx stop
      if [ -d '.dfx' ]; then 
        rm -rf .dfx 
      fi; 
      if [ -d 'dist' ]; then 
        rm -rf dist 
      fi
    displayName: 'Cleanup'
    condition: always()
