steps:
  - bash: |
      NEW_ARTIFACT_TIMESTAMP="$(date "+%s")"
      echo "##vso[task.setvariable variable=ARTIFACT_TIMESTAMP]${NEW_ARTIFACT_TIMESTAMP}"
    displayName: 'Preparation: evaluate ARTIFACT_TIMESTAMP'

  - bash: |
      NEW_ARTIFACT_DATETIME="$(date "+%Y-%m-%dT%H:%M:%S")"
      echo "##vso[task.setvariable variable=ARTIFACT_DATETIME]${NEW_ARTIFACT_DATETIME}"
    displayName: 'Preparation: evaluate ARTIFACT_DATETIME'
