#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

SKIP_ALL_STEPS="${SKIP_ALL_STEPS:-false}"

if [ "${SKIP_ALL_STEPS}" = 'true' ]; then
    echo "SKIP_ALL_STEPS = '${SKIP_ALL_STEPS}'"
    exit 0
fi

echo ">> Run git 'pre-push' hook <<"

echo "INFO:  Check code quality tooling exists"
if ! which yarn >/dev/null 2>&1; then
  echo "ERROR: could not locate yarn"
  exit 1
fi

echo "INFO:  Check javascript codebase"
echo "  - yarn code:style"
if ! $(which yarn) code:style >/dev/null 2>&1; then
  echo "ERROR: 'yarn code:style' check failed, abort pushing"
  echo "       consider running 'yarn code:style:fix'"
  echo
  exit 1
fi

echo "  - yarn code:analyse"
if ! $(which yarn) code:analyse >/dev/null 2>&1; then
  echo "ERROR: 'yarn code:analyse' check failed, abort pushing"
  echo
  exit 1
fi

# @warn disable for now
#echo "  - yarn code:test"
#if ! $(which yarn) code:test >/dev/null 2>&1; then
#  echo "ERROR: 'yarn code:test' check failed, abort pushing"
#  echo
#  exit 1
#fi
